{{- if .Values.cloud.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "cloud-agent.fullname" . }}-cloud-data
  labels:
    {{- include "cloud-agent.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.cloud.persistence.size }}
  {{- if .Values.cloud.persistence.storageClass }}
  storageClassName: {{ .Values.cloud.persistence.storageClass }}
  {{- end }}
{{- end }}

