{{- if .Values.ui.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tiangong-deploy.fullname" . }}-ui
  labels:
    {{- include "tiangong-deploy.labels" . | nindent 4 }}
    app.kubernetes.io/component: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "tiangong-deploy.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: ui
  template:
    metadata:
      labels:
        {{- include "tiangong-deploy.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: ui
    spec:
      containers:
      - name: ui
        image: "{{ .Values.ui.image.repository }}:{{ .Values.ui.image.tag }}"
        imagePullPolicy: {{ .Values.ui.image.pullPolicy }}
        ports:
        - containerPort: 80
          protocol: TCP
        env:
        - name: CLOUD_API_URL
          value: {{ .Values.ui.cloudURL | quote }}
        - name: CLOUD_WS_URL
          value: {{ .Values.ui.cloudURL | quote }}
        resources:
          {{- toYaml .Values.ui.resources | nindent 10 }}
{{- end }}
