{{- if .Values.ui.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "tiangong-deploy.fullname" . }}-ui
  labels:
    {{- include "tiangong-deploy.labels" . | nindent 4 }}
    app.kubernetes.io/component: ui
spec:
  type: {{ .Values.ui.service.type }}
  ports:
  - port: {{ .Values.ui.service.port }}
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    {{- include "tiangong-deploy.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: ui
{{- end }}
